### ISSUE TITLE
Rotate

### ISSUE THREAD

**Issue by Lenacus** [weihanchen/angular-d3-word-cloud#4]
Hi,

How to disable rotation ?

Thanks

**Comment by weihanchen** [comment]
Rotation option not supported currently, and i will try to add this option on next release.

**Comment by weihanchen** [comment]
@Lenacus This library has already release v0.4.0 and you can add `rotate` option to set rotation with `0` like below:
```html
<div id="wordsCloud">
   <word-cloud words="appCtrl.words" width="appCtrl.width" height="appCtrl.height" padding="5" rotate="0" on-click="appCtrl.wordClicked">
   </word-cloud>
</div>
```

**Comment by Lenacus** [comment]
Awesome !

Thanks a lot of 👍
