### ISSUE TITLE
Angular 2

### ISSUE THREAD

**Issue by karinpm** [weihanchen/angular-d3-word-cloud#5]
Any chance you have an angular 2 implementation?

**Comment by weihanchen** [comment]
I will try to implement with angular2 in a few months.
Thanks for your suggestion.

**Comment by logstown** [comment]
Hi, any updates on this?

**Comment by markfullmer** [comment]
Here's an Angular2 alternative: https://www.npmjs.com/package/angular-tag-cloud-module
