### ISSUE TITLE
Tooltips on mouseover

### ISSUE THREAD

**Issue by venkat-subramani** [weihanchen/angular-d3-word-cloud#6]
The library has some css effects on mouseover of the word, thats great.
Any suggestions about adding custom tooltip on mouseover of words.

Thanks

**Comment by weihanchen** [comment]
Thanks for your suggestion, i will try to design this feature.

**Comment by khoramshahy** [comment]
hi, I wanted to ask adding tooltip to word-cloud is in progress or it has been canceled?

**Comment by einali** [comment]
please new update !!

**Comment by weihanchen** [comment]
Version 0.5.0 has introduced a new option named `use-tooltip` which is include default tooltip template.
Here's an example
```javascript
<div id="wordsCloud">
   <word-cloud words="appCtrl.words" width="appCtrl.width" height="appCtrl.height" padding="5" rotate="appCtrl.rotate" use-tooltip="true"  use-transition="appCtrl.useTransition" on-click="appCtrl.wordClicked">
   </word-cloud>
</div>
```
